# Generated by Django 3.0.6 on 2020-06-21 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='weight_menu',
            new_name='menu_name',
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_record', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('weight_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weight.Menu')),
            ],
        ),
    ]
