# Generated by Django 3.0.6 on 2020-06-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0002_auto_20200621_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
