# Generated by Django 3.0.6 on 2020-07-20 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0004_menu_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='rep',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
