# Generated by Django 3.0.6 on 2020-08-09 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0005_record_rep'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='sets',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
