# Generated by Django 3.0.6 on 2020-08-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0006_record_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='registerd_at',
            field=models.DateField(default='2020-08-09'),
            preserve_default=False,
        ),
    ]
